name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-for-release:
    runs-on: ubuntu-latest
    container:
      image: gocv/opencv:4.10.0
    steps:
    - uses: actions/checkout@v4
    
    - name: Fix ownership issues
      run: git config --global --add safe.directory /__w/FacialRecognition/FacialRecognition
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Build
      run: |
        mkdir -p release
        go build -v -o release/FacialRecognition main.go
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: facial-recognition-linux
        path: release/FacialRecognition
        retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build-for-release
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: facial-recognition-linux
        path: ./release
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}